import type { Product } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-hoodie-01',
    name: 'Oversized Heavyweight Hoodie (Autumn Edition)',
    sku: 'HD-HVY-BLK-L',
    sellingPrice: 78.0,
    cogs: 22.5,
    units: 1200,
    shippingPerUnit: 6.0,
    fulfillmentRate: 84,
    adSpendPerUnit: 24.0,
    totalAdSpend: 28800,
    adSpendMode: 'per-unit',
    fixedCosts: [
      { id: 'fc-1', name: 'Photoshoot & Models', amount: 800 },
      { id: 'fc-2', name: 'Studio & Warehousing Rent', amount: 1200 },
      { id: 'fc-3', name: 'Salaries & Media Buyer', amount: 2500 },
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-earbuds-02',
    name: 'ANC Wireless Pro Earbuds (Noise Cancelling)',
    sku: 'TECH-ANC-PRO-01',
    sellingPrice: 129.0,
    cogs: 34.0,
    units: 850,
    shippingPerUnit: 7.5,
    fulfillmentRate: 91,
    adSpendPerUnit: 38.0,
    totalAdSpend: 32300,
    adSpendMode: 'per-unit',
    fixedCosts: [
      { id: 'fc-4', name: 'Influencer Gifting & UGC', amount: 1500 },
      { id: 'fc-5', name: 'Creative Video Ads Studio', amount: 1800 },
      { id: 'fc-6', name: 'Tech QA & Customer Support', amount: 950 },
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-serum-03',
    name: 'Hydrating Vitamin C Glow Face Serum (50ml)',
    sku: 'GLOW-VITC-50ML',
    sellingPrice: 42.0,
    cogs: 6.8,
    units: 2500,
    shippingPerUnit: 4.5,
    fulfillmentRate: 88,
    adSpendPerUnit: 14.5,
    totalAdSpend: 36250,
    adSpendMode: 'per-unit',
    fixedCosts: [
      { id: 'fc-7', name: 'Product Photography & 3D', amount: 650 },
      { id: 'fc-8', name: 'Lab Certifications & Testing', amount: 900 },
      { id: 'fc-9', name: 'Custom Packaging Design', amount: 1100 },
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-cushion-04',
    name: 'Smart Ergonomic Lumbar Support Cushion',
    sku: 'HOME-ERGO-CUSH-09',
    sellingPrice: 54.0,
    cogs: 14.2,
    units: 600,
    shippingPerUnit: 8.5,
    fulfillmentRate: 76,
    adSpendPerUnit: 26.0,
    totalAdSpend: 15600,
    adSpendMode: 'per-unit',
    fixedCosts: [
      { id: 'fc-10', name: '3D Renderings & Ad Copy', amount: 450 },
      { id: 'fc-11', name: 'Warehousing Overhead', amount: 600 },
    ],
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
